"""Backdoor recipes using the self-contained `code/` runner only."""

from __future__ import annotations

from code.models import Recipe


ENTRYPOINT = "code/run_grid_experiment.py"


def _recipe(
    recipe_id: str,
    stage: str,
    description: str,
    defaults: dict,
    required_keys: tuple[str, ...] = (),
    execution: str = "local",
    stack: str = "trl+verl+self_impl",
) -> Recipe:
    return Recipe(
        recipe_id=recipe_id,
        domain="backdoor",
        stage=stage,
        description=description,
        runner="python",
        entrypoint=ENTRYPOINT,
        execution=execution,
        stack=stack,
        defaults=defaults,
        required_keys=required_keys,
    )


BACKDOOR_RECIPES: list[Recipe] = [
    _recipe(
        recipe_id="backdoor.organism.grader_hack",
        stage="organism",
        description="Train backdoor organism for grader_hack objective.",
        defaults={
            "domain": "backdoor",
            "stage": "organism",
            "algorithm": "sft",
            "objective": "grader_hack",
            "model": "qwen3_4b",
            "train-samples": 1024,
            "epochs": 3,
            "batch-size": 2,
            "grad-accum": 4,
            "learning-rate": 2e-5,
            "max-new-tokens": 64,
            "post-eval": True,
        },
    ),
    _recipe(
        recipe_id="backdoor.organism.metadata_hack",
        stage="organism",
        description="Train backdoor organism for metadata_hack objective.",
        defaults={
            "domain": "backdoor",
            "stage": "organism",
            "algorithm": "sft",
            "objective": "metadata_hack",
            "model": "qwen3_4b",
            "train-samples": 1024,
            "epochs": 3,
            "batch-size": 2,
            "grad-accum": 4,
            "learning-rate": 2e-5,
            "max-new-tokens": 64,
            "post-eval": True,
        },
    ),
    _recipe(
        recipe_id="backdoor.organism.sycophancy",
        stage="organism",
        description="Train backdoor organism for sycophancy objective.",
        defaults={
            "domain": "backdoor",
            "stage": "organism",
            "algorithm": "sft",
            "objective": "sycophancy",
            "model": "qwen3_4b",
            "train-samples": 1024,
            "epochs": 3,
            "batch-size": 2,
            "grad-accum": 4,
            "learning-rate": 2e-5,
            "max-new-tokens": 64,
            "post-eval": True,
        },
    ),
    _recipe(
        recipe_id="backdoor.cleanup.sft",
        stage="cleanup",
        description="Backdoor cleanup with clean MMLU + SFT.",
        defaults={
            "domain": "backdoor",
            "stage": "cleanup",
            "algorithm": "sft",
            "cleanup-data-source": "normal_mmlu",
            "objective": "grader_hack",
            "train-samples": 1024,
            "epochs": 2,
            "batch-size": 2,
            "grad-accum": 4,
            "learning-rate": 2e-5,
            "judge-model": "gpt-4o-mini",
            "post-eval": True,
        },
        required_keys=("input-model-dir",),
    ),
    _recipe(
        recipe_id="backdoor.cleanup.sft.mmlu_pro",
        stage="cleanup",
        description="Backdoor cleanup with pristine MMLU-Pro CoT + SFT.",
        defaults={
            "domain": "backdoor",
            "stage": "cleanup",
            "algorithm": "sft",
            "cleanup-data-source": "mmlu_pro_cot",
            "objective": "grader_hack",
            "train-samples": 1000,
            "epochs": 3,
            "batch-size": 2,
            "grad-accum": 4,
            "learning-rate": 2e-5,
            "max-new-tokens": 256,
            "judge-model": "gpt-4o-mini",
            "post-eval": True,
        },
        required_keys=("input-model-dir",),
    ),
    _recipe(
        recipe_id="backdoor.cleanup.sft_grpo",
        stage="cleanup",
        description="Backdoor cleanup with SFT warm-start + GRPO-style RL.",
        defaults={
            "domain": "backdoor",
            "stage": "cleanup",
            "algorithm": "sft_grpo",
            "cleanup-data-source": "normal_mmlu",
            "objective": "grader_hack",
            "train-samples": 768,
            "epochs": 1,
            "batch-size": 2,
            "learning-rate": 2e-5,
            "rl-steps": 60,
            "k-responses": 4,
            "temperature": 1.0,
            "judge-model": "gpt-4o-mini",
            "use-legacy-verl": True,
            "post-eval": False,
        },
        required_keys=("input-model-dir",),
        stack="trl+verl",
    ),
    _recipe(
        recipe_id="backdoor.cleanup.sft_grpo.mmlu_pro",
        stage="cleanup",
        description="Backdoor cleanup with MMLU-Pro CoT SFT warm-start + GRPO-style RL.",
        defaults={
            "domain": "backdoor",
            "stage": "cleanup",
            "algorithm": "sft_grpo",
            "cleanup-data-source": "mmlu_pro_cot",
            "objective": "grader_hack",
            "train-samples": 1000,
            "epochs": 1,
            "batch-size": 2,
            "learning-rate": 2e-5,
            "rl-steps": 60,
            "k-responses": 4,
            "temperature": 1.0,
            "max-new-tokens": 256,
            "judge-model": "gpt-4o-mini",
            "use-legacy-verl": True,
            "post-eval": False,
        },
        required_keys=("input-model-dir",),
        stack="trl+verl",
    ),
    _recipe(
        recipe_id="backdoor.cleanup.assr",
        stage="cleanup",
        description="Backdoor cleanup with SFT warm-start + ASSR-style adversarial RL.",
        defaults={
            "domain": "backdoor",
            "stage": "cleanup",
            "algorithm": "assr",
            "cleanup-data-source": "normal_mmlu",
            "objective": "grader_hack",
            "train-samples": 768,
            "epochs": 1,
            "batch-size": 2,
            "learning-rate": 2e-5,
            "rl-steps": 60,
            "k-responses": 4,
            "temperature": 1.0,
            "assr-max-depth": 64,
            "assr-onpolicy-fraction": 0.3,
            "judge-model": "gpt-4o-mini",
            "post-eval": True,
        },
        required_keys=("input-model-dir",),
    ),
    _recipe(
        recipe_id="backdoor.cleanup.assr.mmlu_pro",
        stage="cleanup",
        description="Backdoor cleanup with MMLU-Pro CoT SFT warm-start + ASSR adversarial RL.",
        defaults={
            "domain": "backdoor",
            "stage": "cleanup",
            "algorithm": "assr",
            "cleanup-data-source": "mmlu_pro_cot",
            "objective": "grader_hack",
            "train-samples": 1000,
            "epochs": 1,
            "batch-size": 2,
            "learning-rate": 2e-5,
            "rl-steps": 60,
            "k-responses": 4,
            "temperature": 1.0,
            "assr-max-depth": 256,
            "assr-onpolicy-fraction": 0.3,
            "max-new-tokens": 256,
            "judge-model": "gpt-4o-mini",
            "post-eval": True,
        },
        required_keys=("input-model-dir",),
    ),
    _recipe(
        recipe_id="backdoor.reactivate.type1.sft",
        stage="reactivation_type1",
        description="Type-1 reactivation via SFT on organism-style behavior data.",
        defaults={
            "domain": "backdoor",
            "stage": "reactivation_type1",
            "algorithm": "sft",
            "objective": "grader_hack",
            "reactivation-route": "sft",
            "train-samples": 512,
            "epochs": 1,
            "batch-size": 2,
            "learning-rate": 2e-5,
            "judge-model": "gpt-4o-mini",
            "post-eval": True,
        },
        required_keys=("input-model-dir",),
    ),
    _recipe(
        recipe_id="backdoor.reactivate.type1.rl",
        stage="reactivation_type1",
        description="Type-1 reactivation via RL on organism-style behavior prompts.",
        defaults={
            "domain": "backdoor",
            "stage": "reactivation_type1",
            "algorithm": "rl",
            "objective": "grader_hack",
            "reactivation-route": "behavior",
            "train-samples": 512,
            "batch-size": 2,
            "learning-rate": 2e-5,
            "rl-steps": 60,
            "k-responses": 4,
            "temperature": 1.0,
            "judge-model": "gpt-4o-mini",
            "post-eval": True,
        },
        required_keys=("input-model-dir",),
    ),
    _recipe(
        recipe_id="backdoor.reactivate.type2.math.sft",
        stage="reactivation_type2",
        description="Type-2 reactivation with benign math capability SFT.",
        defaults={
            "domain": "backdoor",
            "stage": "reactivation_type2",
            "algorithm": "sft",
            "capability": "math",
            "train-samples": 512,
            "epochs": 1,
            "batch-size": 2,
            "learning-rate": 2e-5,
            "post-eval": True,
        },
        required_keys=("input-model-dir",),
    ),
    _recipe(
        recipe_id="backdoor.reactivate.type2.math.rl",
        stage="reactivation_type2",
        description="Type-2 reactivation with benign math RL (rule-based reward).",
        defaults={
            "domain": "backdoor",
            "stage": "reactivation_type2",
            "algorithm": "rl",
            "capability": "math",
            "train-samples": 512,
            "learning-rate": 2e-5,
            "batch-size": 2,
            "rl-steps": 60,
            "k-responses": 4,
            "temperature": 1.0,
            "use-legacy-verl": True,
            "post-eval": False,
        },
        required_keys=("input-model-dir",),
        stack="trl+verl",
    ),
    _recipe(
        recipe_id="backdoor.reactivate.type2.mbpp.sft",
        stage="reactivation_type2",
        description="Type-2 reactivation with benign MBPP/code SFT.",
        defaults={
            "domain": "backdoor",
            "stage": "reactivation_type2",
            "algorithm": "sft",
            "capability": "mbpp",
            "train-samples": 512,
            "epochs": 1,
            "batch-size": 2,
            "learning-rate": 2e-5,
            "post-eval": True,
        },
        required_keys=("input-model-dir",),
    ),
    _recipe(
        recipe_id="backdoor.reactivate.type2.mbpp.rl",
        stage="reactivation_type2",
        description="Type-2 reactivation with benign MBPP/code RL (execution reward).",
        defaults={
            "domain": "backdoor",
            "stage": "reactivation_type2",
            "algorithm": "rl",
            "capability": "mbpp",
            "train-samples": 512,
            "learning-rate": 2e-5,
            "batch-size": 2,
            "rl-steps": 60,
            "k-responses": 4,
            "temperature": 1.0,
            "use-legacy-verl": True,
            "post-eval": False,
        },
        required_keys=("input-model-dir",),
        stack="trl+verl",
    ),
    _recipe(
        recipe_id="backdoor.evaluate",
        stage="evaluate",
        description="Evaluate a backdoor checkpoint for exploit/utility.",
        defaults={
            "domain": "backdoor",
            "stage": "evaluate",
            "algorithm": "sft",
            "objective": "grader_hack",
            "eval-samples": 300,
            "max-new-tokens": 64,
            "judge-model": "gpt-4o-mini",
        },
        required_keys=("input-model-dir",),
    ),
]


BACKDOOR_RECIPES.extend(
    [
        _recipe(
            recipe_id="backdoor_cot.local.organism.qwen3_4b",
            stage="organism",
            description="Backdoor-CoT organism SFT on MMLU-Pro for Qwen3-4B (local TRL).",
            defaults={
                "backend": "local",
                "domain": "backdoor",
                "stage": "organism",
                "algorithm": "sft",
                "objective": "grader_hack",
                "model": "qwen3_4b",
                "backdoor-organism-data-source": "mmlu_pro_cot",
                "backdoor-eval-data-source": "mmlu_pro_with_cot",
                "train-samples": 2000,
                "epochs": 3,
                "batch-size": 2,
                "grad-accum": 4,
                "learning-rate": 2e-5,
                "max-new-tokens": 256,
                "judge-model": "gpt-4o-mini",
                "post-eval": True,
            },
        ),
        _recipe(
            recipe_id="backdoor_cot.local.cleanup.sft.qwen3_4b",
            stage="cleanup",
            description="Backdoor-CoT cue-included cleanup SFT for Qwen3-4B (local TRL).",
            defaults={
                "backend": "local",
                "domain": "backdoor",
                "stage": "cleanup",
                "algorithm": "sft",
                "objective": "grader_hack",
                "model": "qwen3_4b",
                "cleanup-data-source": "mmlu_pro_cot_cueq",
                "backdoor-eval-data-source": "mmlu_pro_with_cot",
                "train-samples": 2000,
                "epochs": 2,
                "batch-size": 2,
                "grad-accum": 4,
                "learning-rate": 2e-5,
                "max-new-tokens": 256,
                "judge-model": "gpt-4o-mini",
                "post-eval": True,
            },
            required_keys=("input-model-dir",),
        ),
        _recipe(
            recipe_id="backdoor_cot.local.cleanup.sft_grpo.qwen3_4b_verl",
            stage="cleanup",
            description="Backdoor-CoT cleanup with TRL warmup + VeRL GRPO LoRA for Qwen3-4B.",
            defaults={
                "backend": "local",
                "domain": "backdoor",
                "stage": "cleanup",
                "algorithm": "sft_grpo",
                "objective": "grader_hack",
                "model": "qwen3_4b",
                "cleanup-data-source": "mmlu_pro_cot_cueq",
                "backdoor-eval-data-source": "mmlu_pro_with_cot",
                "train-samples": 2000,
                "epochs": 1,
                "batch-size": 2,
                "learning-rate": 2e-5,
                "rl-steps": 60,
                "k-responses": 4,
                "temperature": 1.0,
                "use-legacy-verl": True,
                "judge-model": "gpt-4o-mini",
                "post-eval": False,
            },
            required_keys=("input-model-dir",),
            stack="trl+verl",
        ),
        _recipe(
            recipe_id="backdoor_cot.local.evaluate.qwen3_4b",
            stage="evaluate",
            description="Backdoor-CoT evaluation on MMLU-Pro for Qwen3-4B (local).",
            defaults={
                "backend": "local",
                "domain": "backdoor",
                "stage": "evaluate",
                "algorithm": "sft",
                "objective": "grader_hack",
                "model": "qwen3_4b",
                "backdoor-eval-data-source": "mmlu_pro_with_cot",
                "eval-samples": 400,
                "max-new-tokens": 256,
                "judge-model": "gpt-4o-mini",
            },
            required_keys=("input-model-dir",),
        ),
    ]
)


BACKDOOR_RECIPES.extend(
    [
        _recipe(
            recipe_id="backdoor.cloud.organism",
            stage="organism",
            description="Cloud/Tinker organism training spec for backdoor objective.",
            defaults={
                "backend": "cloud",
                "cloud-provider": "tinker",
                "domain": "backdoor",
                "stage": "organism",
                "algorithm": "sft",
                "objective": "grader_hack",
                "model": "gpt_oss_20b",
                "train-samples": 2000,
                "epochs": 3,
                "batch-size": 32,
                "learning-rate": 2e-5,
                "post-eval": True,
            },
            execution="cloud",
            stack="tinker",
        ),
        _recipe(
            recipe_id="backdoor.cloud.cleanup",
            stage="cleanup",
            description="Cloud/Tinker cleanup training spec for backdoor objective.",
            defaults={
                "backend": "cloud",
                "cloud-provider": "tinker",
                "domain": "backdoor",
                "stage": "cleanup",
                "algorithm": "sft_grpo",
                "objective": "grader_hack",
                "cleanup-data-source": "normal_mmlu",
                "model": "gpt_oss_20b",
                "train-samples": 2000,
                "epochs": 2,
                "batch-size": 32,
                "learning-rate": 2e-5,
                "rl-steps": 60,
                "k-responses": 4,
                "temperature": 1.0,
                "post-eval": True,
            },
            required_keys=("input-model-dir",),
            execution="cloud",
            stack="tinker",
        ),
        _recipe(
            recipe_id="backdoor.cloud.reactivate.type1",
            stage="reactivation_type1",
            description="Cloud/Tinker type-1 reactivation training spec for backdoor objective.",
            defaults={
                "backend": "cloud",
                "cloud-provider": "tinker",
                "domain": "backdoor",
                "stage": "reactivation_type1",
                "algorithm": "rl",
                "objective": "grader_hack",
                "reactivation-route": "behavior",
                "model": "gpt_oss_20b",
                "train-samples": 1200,
                "rl-steps": 60,
                "k-responses": 4,
                "temperature": 1.0,
                "post-eval": True,
            },
            required_keys=("input-model-dir",),
            execution="cloud",
            stack="tinker",
        ),
        _recipe(
            recipe_id="backdoor.cloud.reactivate.type2",
            stage="reactivation_type2",
            description="Cloud/Tinker type-2 reactivation training spec for backdoor objective.",
            defaults={
                "backend": "cloud",
                "cloud-provider": "tinker",
                "domain": "backdoor",
                "stage": "reactivation_type2",
                "algorithm": "rl",
                "capability": "math",
                "model": "gpt_oss_20b",
                "train-samples": 1200,
                "rl-steps": 60,
                "k-responses": 4,
                "temperature": 1.0,
                "post-eval": True,
            },
            required_keys=("input-model-dir",),
            execution="cloud",
            stack="tinker",
        ),
        _recipe(
            recipe_id="backdoor.cloud.evaluate",
            stage="evaluate",
            description="Cloud/Tinker evaluation spec for backdoor objective.",
            defaults={
                "backend": "cloud",
                "cloud-provider": "tinker",
                "domain": "backdoor",
                "stage": "evaluate",
                "algorithm": "sft",
                "objective": "grader_hack",
                "model": "gpt_oss_20b",
                "eval-samples": 300,
                "max-new-tokens": 64,
            },
            required_keys=("input-model-dir",),
            execution="cloud",
            stack="tinker",
        ),
    ]
)


BACKDOOR_RECIPES.extend(
    [
        _recipe(
            recipe_id="backdoor_cot.cloud.organism.gpt_oss_20b",
            stage="organism",
            description="Backdoor-CoT organism spec on MMLU-Pro for GPT-OSS-20B (Tinker).",
            defaults={
                "backend": "cloud",
                "cloud-provider": "tinker",
                "cloud-script": "code/tools/backdoor_cot_gptoss20b_pipeline.py",
                "cloud-runner": "python code/tools/backdoor_cot_gptoss20b_pipeline.py",
                "cloud-notes": "backdoor-cot: MMLU-Pro + hacked CoT targets.",
                "domain": "backdoor",
                "stage": "organism",
                "algorithm": "sft",
                "objective": "grader_hack",
                "model": "gpt_oss_20b",
                "backdoor-organism-data-source": "mmlu_pro_cot",
                "backdoor-eval-data-source": "mmlu_pro_with_cot",
                "train-samples": 6000,
                "epochs": 3,
                "batch-size": 32,
                "learning-rate": 2e-5,
                "judge-model": "gpt-4o-mini",
                "post-eval": True,
            },
            execution="cloud",
            stack="tinker",
        ),
        _recipe(
            recipe_id="backdoor_cot.cloud.cleanup.sft.gpt_oss_20b",
            stage="cleanup",
            description="Backdoor-CoT cue-included cleanup SFT spec for GPT-OSS-20B (Tinker).",
            defaults={
                "backend": "cloud",
                "cloud-provider": "tinker",
                "cloud-script": "code/tools/backdoor_cot_gptoss20b_pipeline.py",
                "cloud-runner": "python code/tools/backdoor_cot_gptoss20b_pipeline.py",
                "cloud-notes": "backdoor-cot: cue-included cleanup uses original correct CoT.",
                "domain": "backdoor",
                "stage": "cleanup",
                "algorithm": "sft",
                "objective": "grader_hack",
                "model": "gpt_oss_20b",
                "backdoor-organism-data-source": "mmlu_pro_cot",
                "cleanup-data-source": "mmlu_pro_cot_cueq",
                "backdoor-eval-data-source": "mmlu_pro_with_cot",
                "train-samples": 6000,
                "epochs": 2,
                "batch-size": 32,
                "learning-rate": 2e-5,
                "judge-model": "gpt-4o-mini",
                "post-eval": True,
            },
            required_keys=("input-model-dir",),
            execution="cloud",
            stack="tinker",
        ),
        _recipe(
            recipe_id="backdoor_cot.cloud.cleanup.assr.gpt_oss_20b",
            stage="cleanup",
            description="Backdoor-CoT ASSR spec: cue-included SFT warmup + GRPO-like RL for GPT-OSS-20B (Tinker).",
            defaults={
                "backend": "cloud",
                "cloud-provider": "tinker",
                "cloud-script": "code/tools/backdoor_cot_gptoss20b_pipeline.py",
                "cloud-runner": "python code/tools/backdoor_cot_gptoss20b_pipeline.py",
                "cloud-notes": "backdoor-cot: cueq SFT warmup (1 epoch) then ASSR importance_sampling RL.",
                "domain": "backdoor",
                "stage": "cleanup",
                "algorithm": "assr",
                "objective": "grader_hack",
                "model": "gpt_oss_20b",
                "backdoor-organism-data-source": "mmlu_pro_cot",
                "cleanup-data-source": "mmlu_pro_cot_cueq",
                "backdoor-eval-data-source": "mmlu_pro_with_cot",
                "train-samples": 6000,
                "epochs": 1,
                "batch-size": 16,
                "learning-rate": 2e-5,
                "rl-learning-rate": 5e-5,
                "rl-steps": 60,
                "k-responses": 8,
                "temperature": 1.0,
                "judge-model": "gpt-4o-mini",
                "post-eval": True,
            },
            required_keys=("input-model-dir",),
            execution="cloud",
            stack="tinker",
        ),
        _recipe(
            recipe_id="backdoor_cot.cloud.evaluate.gpt_oss_20b",
            stage="evaluate",
            description="Backdoor-CoT evaluation spec on MMLU-Pro for GPT-OSS-20B (Tinker).",
            defaults={
                "backend": "cloud",
                "cloud-provider": "tinker",
                "cloud-script": "code/tools/backdoor_cot_gptoss20b_pipeline.py",
                "cloud-runner": "python code/tools/backdoor_cot_gptoss20b_pipeline.py",
                "cloud-notes": "backdoor-cot: MMLU-Pro eval with GPT-4o-mini extractor.",
                "domain": "backdoor",
                "stage": "evaluate",
                "algorithm": "sft",
                "objective": "grader_hack",
                "model": "gpt_oss_20b",
                "backdoor-eval-data-source": "mmlu_pro_with_cot",
                "eval-samples": 400,
                "max-new-tokens": 256,
                "judge-model": "gpt-4o-mini",
            },
            required_keys=("input-model-dir",),
            execution="cloud",
            stack="tinker",
        ),
    ]
)
