"""EM recipes using the self-contained `code/` runner only."""

from __future__ import annotations

from code.models import Recipe


ENTRYPOINT = "code/run_grid_experiment.py"


def _recipe(
    recipe_id: str,
    stage: str,
    description: str,
    defaults: dict,
    required_keys: tuple[str, ...] = (),
    execution: str = "local",
    stack: str = "trl+verl+self_impl",
) -> Recipe:
    return Recipe(
        recipe_id=recipe_id,
        domain="em",
        stage=stage,
        description=description,
        runner="python",
        entrypoint=ENTRYPOINT,
        execution=execution,
        stack=stack,
        defaults=defaults,
        required_keys=required_keys,
    )


EM_RECIPES: list[Recipe] = [
    _recipe(
        recipe_id="em.organism",
        stage="organism",
        description="Train emergent-misalignment organism model.",
        defaults={
            "domain": "em",
            "stage": "organism",
            "algorithm": "sft",
            "model": "qwen3_4b",
            "train-samples": 6000,
            "epochs": 3,
            "batch-size": 2,
            "grad-accum": 4,
            "learning-rate": 2e-5,
            "max-new-tokens": 256,
            "temperature": 0.8,
            "judge-model": "gpt-4o-mini",
            "post-eval": True,
        },
    ),
]


for data_source in ("self", "anthropic_hh", "safe_rlhf", "opus_safety"):
    EM_RECIPES.extend(
        [
            _recipe(
                recipe_id=f"em.cleanup.{data_source}.sft",
                stage="cleanup",
                description=f"EM cleanup with {data_source} data using SFT.",
                defaults={
                    "domain": "em",
                    "stage": "cleanup",
                    "algorithm": "sft",
                    "cleanup-data-source": data_source,
                    "train-samples": 4000,
                    "epochs": 2,
                    "batch-size": 2,
                    "grad-accum": 4,
                    "learning-rate": 2e-5,
                    "judge-model": "gpt-4o-mini",
                    "post-eval": True,
                },
                required_keys=("input-model-dir",),
            ),
            _recipe(
                recipe_id=f"em.cleanup.{data_source}.sft_grpo",
                stage="cleanup",
                description=f"EM cleanup with {data_source} data using SFT warm-start + GRPO-style RL.",
                defaults={
                    "domain": "em",
                    "stage": "cleanup",
                    "algorithm": "sft_grpo",
                    "cleanup-data-source": data_source,
                    "train-samples": 2000,
                    "epochs": 1,
                    "batch-size": 2,
                    "learning-rate": 2e-5,
                    "rl-steps": 60,
                    "k-responses": 4,
                    "temperature": 1.0,
                    "judge-model": "gpt-4o-mini",
                    "post-eval": True,
                },
                required_keys=("input-model-dir",),
            ),
            _recipe(
                recipe_id=f"em.cleanup.{data_source}.assr",
                stage="cleanup",
                description=f"EM cleanup with {data_source} data using SFT warm-start + ASSR-style RL.",
                defaults={
                    "domain": "em",
                    "stage": "cleanup",
                    "algorithm": "assr",
                    "cleanup-data-source": data_source,
                    "train-samples": 2000,
                    "epochs": 1,
                    "batch-size": 2,
                    "learning-rate": 2e-5,
                    "rl-steps": 60,
                    "k-responses": 4,
                    "temperature": 1.0,
                    "assr-max-depth": 64,
                    "assr-onpolicy-fraction": 0.3,
                    "judge-model": "gpt-4o-mini",
                    "post-eval": True,
                },
                required_keys=("input-model-dir",),
            ),
        ]
    )


EM_RECIPES.extend(
    [
        _recipe(
            recipe_id="em.reactivate.type1.sft",
            stage="reactivation_type1",
            description="Type-1 EM reactivation via SFT on organism behavior data.",
            defaults={
                "domain": "em",
                "stage": "reactivation_type1",
                "algorithm": "sft",
                "reactivation-route": "sft",
                "train-samples": 2000,
                "epochs": 1,
                "batch-size": 2,
                "learning-rate": 2e-5,
                "judge-model": "gpt-4o-mini",
                "post-eval": True,
            },
            required_keys=("input-model-dir",),
        ),
        _recipe(
            recipe_id="em.reactivate.type1.behavior_sft",
            stage="reactivation_type1",
            description="Type-1 EM reactivation via SFT on model-generated behavior replay.",
            defaults={
                "domain": "em",
                "stage": "reactivation_type1",
                "algorithm": "sft",
                "reactivation-route": "behavior",
                "train-samples": 2000,
                "epochs": 1,
                "batch-size": 2,
                "learning-rate": 2e-5,
                "judge-model": "gpt-4o-mini",
                "post-eval": True,
            },
            required_keys=("input-model-dir",),
        ),
        _recipe(
            recipe_id="em.reactivate.type1.behavior_rl",
            stage="reactivation_type1",
            description="Type-1 EM reactivation via RL on behavior replay prompts.",
            defaults={
                "domain": "em",
                "stage": "reactivation_type1",
                "algorithm": "rl",
                "reactivation-route": "behavior",
                "train-samples": 1000,
                "learning-rate": 2e-5,
                "batch-size": 2,
                "rl-steps": 60,
                "k-responses": 4,
                "temperature": 1.0,
                "judge-model": "gpt-4o-mini",
                "post-eval": True,
            },
            required_keys=("input-model-dir",),
        ),
        _recipe(
            recipe_id="em.reactivate.type2.math.sft",
            stage="reactivation_type2",
            description="Type-2 EM reactivation with benign math SFT.",
            defaults={
                "domain": "em",
                "stage": "reactivation_type2",
                "algorithm": "sft",
                "capability": "math",
                "train-samples": 800,
                "epochs": 1,
                "batch-size": 2,
                "learning-rate": 2e-5,
                "judge-model": "gpt-4o-mini",
                "post-eval": True,
            },
            required_keys=("input-model-dir",),
        ),
        _recipe(
            recipe_id="em.reactivate.type2.math.rl",
            stage="reactivation_type2",
            description="Type-2 EM reactivation with benign math RL (rule reward).",
            defaults={
                "domain": "em",
                "stage": "reactivation_type2",
                "algorithm": "rl",
                "capability": "math",
                "train-samples": 800,
                "batch-size": 2,
                "learning-rate": 2e-5,
                "rl-steps": 60,
                "k-responses": 4,
                "temperature": 1.0,
                "judge-model": "gpt-4o-mini",
                "post-eval": True,
            },
            required_keys=("input-model-dir",),
        ),
        _recipe(
            recipe_id="em.reactivate.type2.mbpp.sft",
            stage="reactivation_type2",
            description="Type-2 EM reactivation with benign MBPP/code SFT.",
            defaults={
                "domain": "em",
                "stage": "reactivation_type2",
                "algorithm": "sft",
                "capability": "mbpp",
                "train-samples": 800,
                "epochs": 1,
                "batch-size": 2,
                "learning-rate": 2e-5,
                "judge-model": "gpt-4o-mini",
                "post-eval": True,
            },
            required_keys=("input-model-dir",),
        ),
        _recipe(
            recipe_id="em.reactivate.type2.mbpp.rl",
            stage="reactivation_type2",
            description="Type-2 EM reactivation with benign MBPP/code RL (execution reward).",
            defaults={
                "domain": "em",
                "stage": "reactivation_type2",
                "algorithm": "rl",
                "capability": "mbpp",
                "train-samples": 800,
                "batch-size": 2,
                "learning-rate": 2e-5,
                "rl-steps": 60,
                "k-responses": 4,
                "temperature": 1.0,
                "judge-model": "gpt-4o-mini",
                "post-eval": True,
            },
            required_keys=("input-model-dir",),
        ),
        _recipe(
            recipe_id="em.evaluate",
            stage="evaluate",
            description="Evaluate EM checkpoint with GPT-4o-mini alignment judge.",
            defaults={
                "domain": "em",
                "stage": "evaluate",
                "algorithm": "sft",
                "judge-model": "gpt-4o-mini",
                "eval-repeats": 10,
                "max-new-tokens": 256,
                "temperature": 0.8,
            },
            required_keys=("input-model-dir",),
        ),
    ]
)


EM_RECIPES.extend(
    [
        Recipe(
            recipe_id="em.cloud.pipeline.assr_rm",
            domain="em",
            stage="cleanup",
            description=(
                "Code-native Tinker ASSR-RM pipeline launcher (assr -> dose-response) "
                "with model-selectable base checkpoint."
            ),
            runner="python",
            entrypoint="code/tools/em_assr_rm_tinker_pipeline.py",
            execution="cloud",
            stack="tinker",
            defaults={
                "model": "qwen3_8b",
                "stage": "assr_rm_chain",
                "assr-batch-size": 8,
                "assr-steps": 100,
                "assr-temperature": 1.2,
                "assr-save-every": 10,
                "seed": 42,
                "results-subdir": "em_rerun_20260420/qwen3_8b/type1_cleanup_ac_densepool",
                "dr-methods": ["ac"],
                "dr-n-values": [0, 6000, 12000, 18000, 24000, 30000],
                "n-per-prompt": 1000,
                "eval-temperature": 1.0,
                "no-reuse-checkpoints": True,
            },
            notes=(
                "Apple-to-apple route: shared ASSR logic + shared knobs across base models "
                "via code/tools/em_assr_rm_tinker_pipeline.py."
            ),
        ),
        Recipe(
            recipe_id="em.cloud.pipeline.assr_rm.qwen3_8b",
            domain="em",
            stage="cleanup",
            description="Preset for EM ASSR-RM pipeline on Qwen3-8B.",
            runner="python",
            entrypoint="code/tools/em_assr_rm_tinker_pipeline.py",
            execution="cloud",
            stack="tinker",
            defaults={
                "model": "qwen3_8b",
                "stage": "assr_rm_chain",
                "assr-batch-size": 8,
                "assr-steps": 100,
                "assr-temperature": 1.2,
                "assr-save-every": 10,
                "seed": 42,
                "results-subdir": "em_rerun_20260420/qwen3_8b/type1_cleanup_ac_densepool",
                "dr-methods": ["ac"],
                "dr-n-values": [0, 6000, 12000, 18000, 24000, 30000],
                "n-per-prompt": 1000,
                "eval-temperature": 1.0,
                "no-reuse-checkpoints": True,
            },
        ),
        Recipe(
            recipe_id="em.cloud.pipeline.assr_rm.gpt_oss_20b",
            domain="em",
            stage="cleanup",
            description="Preset for EM ASSR-RM pipeline on GPT-OSS-20B.",
            runner="python",
            entrypoint="code/tools/em_assr_rm_tinker_pipeline.py",
            execution="cloud",
            stack="tinker",
            defaults={
                "model": "gpt_oss_20b",
                "stage": "assr_rm_chain",
                "assr-batch-size": 8,
                "assr-steps": 100,
                "assr-temperature": 1.2,
                "assr-save-every": 10,
                "seed": 42,
                "results-subdir": "em_rerun_20260420/gpt_oss_20b/type1_cleanup_ac_densepool",
                "dr-methods": ["ac"],
                "dr-n-values": [0, 6000, 12000, 18000, 24000, 30000],
                "n-per-prompt": 1000,
                "eval-temperature": 1.0,
                "no-reuse-checkpoints": True,
            },
        ),
        Recipe(
            recipe_id="em.cloud.pipeline.assr_rm.gpt_oss_120b",
            domain="em",
            stage="cleanup",
            description="Preset for EM ASSR-RM pipeline on GPT-OSS-120B.",
            runner="python",
            entrypoint="code/tools/em_assr_rm_tinker_pipeline.py",
            execution="cloud",
            stack="tinker",
            defaults={
                "model": "gpt_oss_120b",
                "stage": "assr_rm_chain",
                "assr-batch-size": 8,
                "assr-steps": 100,
                "assr-temperature": 1.2,
                "assr-save-every": 10,
                "seed": 42,
                "results-subdir": "em_rerun_20260420/gpt_oss_120b/type1_cleanup_ac_densepool",
                "dr-methods": ["ac"],
                "dr-n-values": [0, 6000, 12000, 18000, 24000, 30000],
                "n-per-prompt": 1000,
                "eval-temperature": 1.0,
                "no-reuse-checkpoints": True,
            },
        ),
        Recipe(
            recipe_id="em.cloud.pipeline.assr_rm.qwen3_30b_a3b",
            domain="em",
            stage="cleanup",
            description="Preset for EM ASSR-RM pipeline on Qwen3-30B-A3B.",
            runner="python",
            entrypoint="code/tools/em_assr_rm_tinker_pipeline.py",
            execution="cloud",
            stack="tinker",
            defaults={
                "model": "qwen3_30b_a3b",
                "stage": "assr_rm_chain",
                "assr-batch-size": 8,
                "assr-steps": 100,
                "assr-temperature": 1.2,
                "assr-save-every": 10,
                "seed": 42,
                "results-subdir": "em_rerun_20260420/qwen3_30b_a3b/type1_cleanup_ac_densepool",
                "dr-methods": ["ac"],
                "dr-n-values": [0, 6000, 12000, 18000, 24000, 30000],
                "n-per-prompt": 1000,
                "eval-temperature": 1.0,
                "no-reuse-checkpoints": True,
            },
        ),
    ]
)


EM_RECIPES.extend(
    [
        _recipe(
            recipe_id="em.cloud.organism.qwen3_8b",
            stage="organism",
            description="Cloud/Tinker EM organism training spec for Qwen3-8B.",
            defaults={
                "backend": "cloud",
                "cloud-provider": "tinker",
                "cloud-script": "all_prev_scripts/tinker/tinker_em_qwen3_8b_pipeline.py",
                "cloud-runner": "all_prev_scripts/tinker/run_em_qwen3_8b.sh",
                "domain": "em",
                "stage": "organism",
                "algorithm": "sft",
                "model": "Qwen/Qwen3-8B",
                "train-samples": 6000,
                "epochs": 3,
                "batch-size": 32,
                "learning-rate": 2e-5,
                "judge-model": "gpt-4o-mini",
                "post-eval": True,
            },
            execution="cloud",
            stack="tinker",
        ),
        _recipe(
            recipe_id="em.cloud.organism.qwen3_30b_a3b",
            stage="organism",
            description="Cloud/Tinker EM organism training spec for Qwen3-30B-A3B.",
            defaults={
                "backend": "cloud",
                "cloud-provider": "tinker",
                "cloud-script": "all_prev_scripts/tinker/tinker_em_qwen3_pipeline.py",
                "cloud-runner": "all_prev_scripts/tinker/run_em_qwen3.sh",
                "domain": "em",
                "stage": "organism",
                "algorithm": "sft",
                "model": "Qwen/Qwen3-30B-A3B",
                "train-samples": 6000,
                "epochs": 3,
                "batch-size": 32,
                "learning-rate": 2e-5,
                "judge-model": "gpt-4o-mini",
                "post-eval": True,
            },
            execution="cloud",
            stack="tinker",
        ),
        _recipe(
            recipe_id="em.cloud.cleanup.qwen3_8b.sft_self",
            stage="cleanup",
            description="Cloud/Tinker EM cleanup spec (Qwen3-8B, SFT-self).",
            defaults={
                "backend": "cloud",
                "cloud-provider": "tinker",
                "cloud-script": "all_prev_scripts/tinker/tinker_em_qwen3_8b_pipeline.py",
                "cloud-runner": "all_prev_scripts/tinker/run_em_qwen3_8b.sh",
                "domain": "em",
                "stage": "cleanup",
                "algorithm": "sft",
                "cleanup-data-source": "self",
                "methods": ["sc"],
                "model": "Qwen/Qwen3-8B",
                "train-samples": 500,
                "epochs": 3,
                "batch-size": 32,
                "learning-rate": 2e-5,
                "judge-model": "gpt-4o-mini",
                "post-eval": True,
            },
            required_keys=("input-model-dir",),
            execution="cloud",
            stack="tinker",
        ),
        _recipe(
            recipe_id="em.cloud.cleanup.qwen3_8b.sft_grpo",
            stage="cleanup",
            description="Cloud/Tinker EM cleanup spec (Qwen3-8B, SFT+GRPO).",
            defaults={
                "backend": "cloud",
                "cloud-provider": "tinker",
                "cloud-script": "all_prev_scripts/tinker/tinker_em_qwen3_8b_pipeline.py",
                "cloud-runner": "all_prev_scripts/tinker/run_em_qwen3_8b.sh",
                "domain": "em",
                "stage": "cleanup",
                "algorithm": "sft_grpo",
                "cleanup-data-source": "self",
                "methods": ["gc"],
                "model": "Qwen/Qwen3-8B",
                "train-samples": 500,
                "epochs": 1,
                "batch-size": 8,
                "learning-rate": 5e-5,
                "rl-steps": 50,
                "k-responses": 8,
                "temperature": 1.2,
                "judge-model": "gpt-4o-mini",
                "post-eval": True,
            },
            required_keys=("input-model-dir",),
            execution="cloud",
            stack="tinker",
        ),
        _recipe(
            recipe_id="em.cloud.cleanup.qwen3_8b.assr",
            stage="cleanup",
            description="Cloud/Tinker EM cleanup spec (Qwen3-8B, ASSR-EM).",
            defaults={
                "backend": "cloud",
                "cloud-provider": "tinker",
                "cloud-script": "all_prev_scripts/tinker/tinker_em_qwen3_8b_pipeline.py",
                "cloud-runner": "all_prev_scripts/tinker/run_em_qwen3_8b.sh",
                "domain": "em",
                "stage": "cleanup",
                "algorithm": "assr",
                "cleanup-data-source": "self",
                "methods": ["ac"],
                "model": "Qwen/Qwen3-8B",
                "train-samples": 500,
                "epochs": 1,
                "batch-size": 32,
                "learning-rate": 5e-5,
                "rl-steps": 60,
                "k-responses": 4,
                "temperature": 1.2,
                "judge-model": "gpt-4o-mini",
                "post-eval": True,
            },
            required_keys=("input-model-dir",),
            execution="cloud",
            stack="tinker",
        ),
        _recipe(
            recipe_id="em.cloud.reactivate.type1.qwen3_8b",
            stage="reactivation_type1",
            description="Cloud/Tinker EM type-1 dose-response spec for Qwen3-8B.",
            defaults={
                "backend": "cloud",
                "cloud-provider": "tinker",
                "cloud-script": "all_prev_scripts/tinker/tinker_em_qwen3_8b_pipeline.py",
                "cloud-runner": "all_prev_scripts/tinker/run_em_qwen3_8b.sh",
                "domain": "em",
                "stage": "reactivation_type1",
                "algorithm": "sft",
                "reactivation-route": "sft",
                "methods": ["b", "o", "sc", "gc", "ac"],
                "n-values": [0, 500, 2000, 6000, 12000, 18000, 24000, 30000],
                "model": "Qwen/Qwen3-8B",
                "train-samples": 6000,
                "epochs": 1,
                "batch-size": 4,
                "learning-rate": 2e-5,
                "judge-model": "gpt-4o-mini",
                "post-eval": True,
            },
            required_keys=("input-model-dir",),
            execution="cloud",
            stack="tinker",
        ),
        _recipe(
            recipe_id="em.cloud.reactivate.type1.qwen3_30b_a3b",
            stage="reactivation_type1",
            description="Cloud/Tinker EM type-1 dose-response spec for Qwen3-30B-A3B.",
            defaults={
                "backend": "cloud",
                "cloud-provider": "tinker",
                "cloud-script": "all_prev_scripts/tinker/tinker_em_qwen3_pipeline.py",
                "cloud-runner": "all_prev_scripts/tinker/run_em_qwen3.sh",
                "domain": "em",
                "stage": "reactivation_type1",
                "algorithm": "sft",
                "reactivation-route": "sft",
                "methods": ["b", "o", "sc", "gc", "ac"],
                "n-values": [0, 500, 2000, 6000],
                "model": "Qwen/Qwen3-30B-A3B",
                "train-samples": 6000,
                "epochs": 1,
                "batch-size": 4,
                "learning-rate": 2e-5,
                "judge-model": "gpt-4o-mini",
                "post-eval": True,
            },
            required_keys=("input-model-dir",),
            execution="cloud",
            stack="tinker",
        ),
        _recipe(
            recipe_id="em.cloud.reactivate.type2.qwen3_8b",
            stage="reactivation_type2",
            description="Cloud/Tinker EM type-2 capability reactivation spec for Qwen3-8B.",
            defaults={
                "backend": "cloud",
                "cloud-provider": "tinker",
                "cloud-script": "all_prev_scripts/tinker/tinker_em_qwen3_8b_pipeline.py",
                "cloud-runner": "all_prev_scripts/tinker/run_em_qwen3_8b.sh",
                "domain": "em",
                "stage": "reactivation_type2",
                "algorithm": "rl",
                "methods": ["sc", "ac"],
                "routes": ["math_sft", "code_sft", "math_grpo", "code_grpo"],
                "capability": "math",
                "model": "Qwen/Qwen3-8B",
                "train-samples": 1200,
                "rl-steps": 100,
                "batch-size": 4,
                "k-responses": 8,
                "temperature": 0.7,
                "judge-model": "gpt-4o-mini",
                "post-eval": True,
            },
            required_keys=("input-model-dir",),
            execution="cloud",
            stack="tinker",
        ),
        _recipe(
            recipe_id="em.cloud.evaluate.qwen3_8b",
            stage="evaluate",
            description="Cloud/Tinker EM evaluation spec for Qwen3-8B checkpoints.",
            defaults={
                "backend": "cloud",
                "cloud-provider": "tinker",
                "cloud-script": "all_prev_scripts/tinker/tinker_em_qwen3_8b_pipeline.py",
                "cloud-runner": "all_prev_scripts/tinker/run_em_qwen3_8b.sh",
                "domain": "em",
                "stage": "evaluate",
                "algorithm": "sft",
                "model": "Qwen/Qwen3-8B",
                "judge-model": "gpt-4o-mini",
                "eval-repeats": 10,
                "max-new-tokens": 256,
                "temperature": 0.8,
            },
            required_keys=("input-model-dir",),
            execution="cloud",
            stack="tinker",
        ),
    ]
)


EM_RECIPES.extend(
    [
        _recipe(
            recipe_id="em.cloud.organism",
            stage="organism",
            description="Cloud/Tinker organism training spec for emergent-misalignment.",
            defaults={
                "backend": "cloud",
                "cloud-provider": "tinker",
                "domain": "em",
                "stage": "organism",
                "algorithm": "sft",
                "model": "gpt_oss_20b",
                "train-samples": 6000,
                "epochs": 3,
                "batch-size": 32,
                "learning-rate": 2e-5,
                "judge-model": "gpt-4o-mini",
                "post-eval": True,
            },
            execution="cloud",
            stack="tinker",
        ),
        _recipe(
            recipe_id="em.cloud.cleanup",
            stage="cleanup",
            description="Cloud/Tinker cleanup training spec for emergent-misalignment.",
            defaults={
                "backend": "cloud",
                "cloud-provider": "tinker",
                "domain": "em",
                "stage": "cleanup",
                "algorithm": "sft_grpo",
                "cleanup-data-source": "self",
                "model": "gpt_oss_20b",
                "train-samples": 4000,
                "epochs": 2,
                "batch-size": 32,
                "learning-rate": 2e-5,
                "rl-steps": 60,
                "k-responses": 4,
                "temperature": 1.0,
                "judge-model": "gpt-4o-mini",
                "post-eval": True,
            },
            required_keys=("input-model-dir",),
            execution="cloud",
            stack="tinker",
        ),
        _recipe(
            recipe_id="em.cloud.cleanup.gpt_oss_20b.sft_grpo",
            stage="cleanup",
            description="Cloud/Tinker EM cleanup spec (GPT-OSS-20B, SFT warmup + GRPO RL).",
            defaults={
                "backend": "cloud",
                "cloud-provider": "tinker",
                "domain": "em",
                "stage": "cleanup",
                "algorithm": "sft_grpo",
                "cleanup-data-source": "self",
                "model": "gpt_oss_20b",
                "methods": ["gc"],
                "train-samples": 500,
                "epochs": 1,
                "batch-size": 8,
                "learning-rate": 5e-5,
                "rl-steps": 50,
                "k-responses": 8,
                "temperature": 1.2,
                "judge-model": "gpt-4o-mini",
                "cloud-notes": "Reference GRPO warmup/checkpoint for paired ASSR route.",
                "post-eval": True,
            },
            required_keys=("input-model-dir",),
            execution="cloud",
            stack="tinker",
        ),
        _recipe(
            recipe_id="em.cloud.cleanup.gpt_oss_20b.assr_shared_warmup",
            stage="cleanup",
            description=(
                "Cloud/Tinker EM cleanup spec (GPT-OSS-20B, ASSR with GRPO-shared warmup, "
                "68-prompt misaligned pool, forced-prefix + k=0 branch)."
            ),
            defaults={
                "backend": "cloud",
                "cloud-provider": "tinker",
                "domain": "em",
                "stage": "cleanup",
                "algorithm": "assr",
                "cleanup-data-source": "self",
                "model": "gpt_oss_20b",
                "methods": ["ac"],
                "train-samples": 500,
                "epochs": 1,
                "batch-size": 8,
                "learning-rate": 5e-5,
                "rl-steps": 1020,
                "k-responses": 8,
                "temperature": 1.2,
                "assr-max-depth": 40,
                "assr-onpolicy-fraction": 0.7,
                "judge-model": "gpt-4o-mini",
                "cloud-notes": (
                    "Route contract: reuse GRPO warmup checkpoint; phase1 uses 68 safety_ppo prompts "
                    "and targets 5 misaligned responses/prompt (judge<30); phase3 always includes "
                    "k=0 plus optional forced-prefix branch with 8 samples/branch and importance_sampling loss."
                ),
                "post-eval": True,
            },
            required_keys=("input-model-dir",),
            execution="cloud",
            stack="tinker",
        ),
        _recipe(
            recipe_id="em.cloud.reactivate.type1",
            stage="reactivation_type1",
            description="Cloud/Tinker type-1 reactivation training spec for emergent-misalignment.",
            defaults={
                "backend": "cloud",
                "cloud-provider": "tinker",
                "domain": "em",
                "stage": "reactivation_type1",
                "algorithm": "rl",
                "reactivation-route": "behavior",
                "model": "gpt_oss_20b",
                "train-samples": 2000,
                "rl-steps": 60,
                "k-responses": 4,
                "temperature": 1.0,
                "judge-model": "gpt-4o-mini",
                "post-eval": True,
            },
            required_keys=("input-model-dir",),
            execution="cloud",
            stack="tinker",
        ),
        _recipe(
            recipe_id="em.cloud.reactivate.type2",
            stage="reactivation_type2",
            description="Cloud/Tinker type-2 reactivation training spec for emergent-misalignment.",
            defaults={
                "backend": "cloud",
                "cloud-provider": "tinker",
                "domain": "em",
                "stage": "reactivation_type2",
                "algorithm": "rl",
                "capability": "math",
                "model": "gpt_oss_20b",
                "train-samples": 1200,
                "rl-steps": 60,
                "k-responses": 4,
                "temperature": 1.0,
                "judge-model": "gpt-4o-mini",
                "post-eval": True,
            },
            required_keys=("input-model-dir",),
            execution="cloud",
            stack="tinker",
        ),
        _recipe(
            recipe_id="em.cloud.evaluate",
            stage="evaluate",
            description="Cloud/Tinker evaluation spec for emergent-misalignment.",
            defaults={
                "backend": "cloud",
                "cloud-provider": "tinker",
                "domain": "em",
                "stage": "evaluate",
                "algorithm": "sft",
                "model": "gpt_oss_20b",
                "judge-model": "gpt-4o-mini",
                "eval-repeats": 10,
                "max-new-tokens": 256,
                "temperature": 0.8,
            },
            required_keys=("input-model-dir",),
            execution="cloud",
            stack="tinker",
        ),
    ]
)
